### ISSUE TITLE
realtime not affecting other clients

### ISSUE THREAD

**Issue by timvandesteeg** [mean-expert-official/loopback-component-realtime#19]
First of all a big thumbs up for all the work Jonathan.
I really enjoyed all the tutorials on the mean expert website and now that most angular projects use the same versions it is really a breeze to setup :)!

I got things running with the pubsub version of the SDK (e.g. roomApi), but got some trouble with the Fireloop version. Correct me if I'm wrong, but based on the documentation I assumed that Fireloop would sync changes in the model real-time between clients. 

As an example, I made a component that fetches Room-data via Fireloop and that has an option to add new Rooms. If I open that component in two tabs and I add a room in one tab, shouldn't the second tab sync and get the update via Fireloop?

```
import { Component, OnInit } from '@angular/core';
import { Room, FireLoopRef }  from '../../shared/sdk/models';
import { RealTime } from '../../shared/sdk/services';

@Component({
  selector: 'app-test2',
  templateUrl: './test2.component.html',
})
export class Test2Component implements OnInit {
  private RoomReference: FireLoopRef<Room>;
  private rooms: Room[];
  
  constructor(private realTime: RealTime) {
    this.RoomReference = this.realTime.FireLoop.ref<Room>(Room);
    this.getAllRooms();
  }  

    //test getting room
    getAllRooms(): void {
        this.RoomReference.on('value').subscribe((rooms: Array<Room>) => {
          console.log('rooms', rooms);
          this.rooms = rooms; 
        });

    }

    public addRoom(event): void {
        var room: Room = new Room({ name: 'New Room' });

        this.RoomReference.create(room).subscribe((instance: Room) => console.log(instance));
    }

  ngOnInit() {
  }

}

```

**Comment by jonathan-casarrubias** [comment]
Hi @timvandesteeg, thanks for reaching me out!.

Hey so, yes it should sync the clients, yesterday I did a big refactor so I believe I broke that part, I have just verified and it does not sync, I will set this as a bug and send the fix ASAP.

Thanks for contributing with the issue.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
Hi @timvandesteeg I have fixed the issue, now all of your clients should be in sync.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
by the way... Im going to write a blog about it, but you should stop creating your list references. in this case the private rooms: Room[] is unnecessary.

You can directly use the FireLoop reference to be rendered in the front end.

Todo example app:

````js
import { Component } from '@angular/core';
import { Todo, FireLoopRef } from './shared/sdk/models';
import { RealTime } from './shared/sdk/services';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  title = 'TODO Application';

  private todo      : Todo = new Todo();
  private reference : FireLoopRef<Todo>;

  constructor(private rt: RealTime) {
    this.reference = this.rt.FireLoop.ref<Todo>(Todo);
  }

  add(): void {
    this.reference.create(this.todo).subscribe(() => this.todo = new Todo());
  }

  update(todo: Todo): void {
    this.reference.upsert(todo).subscribe();
  }

  remove(todo: Todo): void {
    this.reference.remove(todo).subscribe();
  }
}
````

Todo example app view

````html
<h1>
  {{title}}
</h1>
<form (submit)="add()">
  <input type="text" name="todo" [(ngModel)]="todo.text" placeholder="Add Todo" />
  <button>Add</button>
</form>
<ul>
  <li *ngFor="let todo of reference.on('changes') | async">
    <input type="text" name="todo" [(ngModel)]="todo.text" />
    <button (click)="update(todo)">update</button>
    <button (click)="remove(todo)">remove</button>
  </li>
</ul>
````

This is super cool that you don't need to do other than passing the FireLoop reference event to the ngFor.

When showing lists.. I recommend the event `changes` over `value` because this way it will be fired on any change, like adding, updating or removing.. It is just great for real time lists.

Test the super compact code Im sharing and you will see how awesome it is.

Cheers
Jon

**Comment by timvandesteeg** [comment]
Yes, everything seems to work now :) Good job mate.
Got both examples running. Very clean and pure coding, I love it!

Only change I had to make was changing the type for the observable:

`private todos: Observable<Todo | Todo[]>;`
