### ISSUE TITLE
IMPLEMENT ACL FUNCTIONALITY

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-component-realtime#21]

**Comment by tabvn** [comment]
Jonathan, if you are looking for this featured i have done this https://github.com/tabvn/loopbackCMS 
see Video how it works: https://www.youtube.com/watch?v=z38B_iA4fJI

**Comment by jonathan-casarrubias** [comment]
@tabvn thanks for sharing, the standard default ACL functionality from loopback  is already implemented within this module, but we have seen other cool modules that improve the ACLs, we might want to add these to the roadmap.

So Ill check your information and see if anything can be later implemented, again thanks for sharing!

Cheers
Jon

**Comment by tabvn** [comment]
@jonathan-casarrubias (y)
