### ISSUE TITLE
Access via Fireloop without authentication

### ISSUE THREAD

**Issue by mike-packetwerk** [mean-expert-official/loopback-component-realtime#25]
This line:
https://github.com/mean-expert-official/loopback-component-realtime/blob/master/src/modules/FireLoop.ts#L184
is not protected by checking the authorization token it seems to me.

This of course means someone has complete access to the database without authorization. Ooops!

**Comment by tabvn** [comment]
same for me.

**Comment by jonathan-casarrubias** [comment]
Very good observation!!! thanks, you might now that the rest of events are protected, but obviously this sneaky one went out without being protected.

I'll send a patch for this asap.

Cheers
Jon
