### ISSUE TITLE
Wrong mixin path in README

### ISSUE THREAD

**Issue by anselanza** [mean-expert-official/loopback-component-realtime#32]
According to the README, the PubSub mixin path should be defined in `model-config.json` as:
```
      "../node_modules/loopback-component-realtime/dist/mixins"
```
However, the `npm install` will actually put the files in:
```
      "../node_modules/@mean-expert/loopback-component-realtime/dist/mixins"
```
Mind if I submit a Pull Request to update this?

**Comment by jonathan-casarrubias** [comment]
@anselanza thanks for this PR. I'm closing this issue now
