### ISSUE TITLE
Propagate AccessToken from RealTime events

### ISSUE THREAD

**Issue by jonathan-casarrubias** [mean-expert-official/loopback-component-realtime#35]
Currently, access token is not being included in the context options to make accessToken available in operation hooks

**Comment by rekless5** [comment]
@jonathan-casarrubias I was trying to access the access token in ctx.options in the 'access' or 'loaded' hooks but it returns undefined. When I do a get request without socket it is then available. Is there a configuration needed for this, or is it available in a different place? Thank you.

**Comment by jonathan-casarrubias** [comment]
@rekless5 the only way for you to get an access token is if you already authenticated the client, if it is now undefined it means the token is not arriving through the websocket channel.

When you login your client sdk, it will persist in cookies the token and you need to make sure  auth: true in the component-config.json file
