### ISSUE TITLE
Angular 2 sdk change event isn't fired when new create is triggered

### ISSUE THREAD

**Issue by rekless5** [mean-expert-official/loopback-component-realtime#42]
mac Sierra 10.12.6 
node.js v8.2.1
@angular/cli: 1.2.7
Loopback 3

I really would like to use this component but I can't seem to get it to work.

The list for 'change' event only fires on load page but not after a new item is created. Symptoms sounds as if I didn't add FireLoop:true to the model json but it's there and I;m really not sure what I'm doing wrong. Here's a repo of a test I reproduced this issue in.

Appreciate it in advanced.

https://github.com/rekless5/realtimetest

**Comment by jonathan-casarrubias** [comment]
hi @rekless5 thanks for reaching out, 

Hey so.. it does sound like the FireLoop mixin is not there, but I see in your repo you added. I was unable to see the front-end part since it is a git sub-module is not commited.

The servers seems to be right, you might also want to enable the debug mode within the component-config file

**Comment by rekless5** [comment]
@jonathan-casarrubias My apologies, just added the client to the repo.

The debug would was Todo change broadcasting. but would not receive it from angular. Maybe I have something wrong there?

**Comment by jonathan-casarrubias** [comment]
@rekless5 thanks for adding the client part, please update as follows:

````js
import { Component } from '@angular/core';
import { Todo, FireLoopRef } from './shared/sdk/models';
import { RealTime } from './shared/sdk/services';
import { Observable } from "rxjs/Observable";
import { Subscription } from "rxjs/Subscription";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  title = 'TODO Application';

  private todo      : Todo = new Todo();
  private todos     : Observable<Todo[]>;
  private reference : FireLoopRef<Todo>;
  private subscription: Subscription;

  constructor(private rt: RealTime) {
    this.rt.onReady().subscribe(()=>{
      this.reference = this.rt.FireLoop.ref<Todo>(Todo);
      // You need to subscribe the event and also save a reference of your subscriptions
      // see ngOnDestroy I added below
      this.subscription = this.reference.on('change')
                                                             .subscribe((todos: Todo[]) => this.todos = todos);
    });
  }

  add(): void {
    this.reference.create(this.todo).subscribe(() => this.todo = new Todo());
  }

  update(todo: Todo): void {
    this.reference.upsert(todo).subscribe();
  }

  remove(todo: Todo): void {
    this.reference.remove(todo).subscribe();
  }
  // This is super important to avoid memory leaks
  // The validations are required since not always the reference or subscription will
  // be available on destroy
  ngOnDestroy() {
    if (this.reference) this.reference.dispose();
    if (this.subscription) this.subscription.dispose();
  }
}
````

That should work, but when you go further in development and you require to enable security, you would do something more like

````js
import { Component } from '@angular/core';
import { Todo, FireLoopRef } from './shared/sdk/models';
import { RealTime } from './shared/sdk/services';
import { Observable } from "rxjs/Observable";
import { Subscription } from "rxjs/Subscription";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  title = 'TODO Application';

  private todo      : Todo = new Todo();
  private todos     : Observable<Todo[]>;
  private reference : FireLoopRef<Todo>;
  private subscription: Subscription;

  constructor(private rt: RealTime) {
    if (
      this.rt.connection.isConnected() &&
      this.rt.connection.authenticated
    ) {
      this.rt.onReady().subscribe(() => this.setup());
    } else {
      this.rt.onReady().subscribe();
      this.rt.onAuthenticated().subscribe(() => this.setup());
    }
  }

  setup() {
    // Make sure you always start clean by disposing fireloop
    this.disposeFL();
    this.reference = this.rt.FireLoop.ref<Todo>(Todo);
    this.subscription = this.reference.on('change')
                                                           .subscribe((todos: Todo[]) => this.todos = todos);
  }

  add(): void {
    this.reference.create(this.todo).subscribe(() => this.todo = new Todo());
  }

  update(todo: Todo): void {
    this.reference.upsert(todo).subscribe();
  }

  remove(todo: Todo): void {
    this.reference.remove(todo).subscribe();
  }

  disposeFL() {
    if (this.reference) this.reference.dispose();
    if (this.subscription) this.subscription.dispose();
  }
  // This is super important to avoid memory leaks
  // The validations are required since not always the reference or subscription will
  // be available on destroy
  ngOnDestroy() {
    // You might need to destroy other things unrelated to fireloop here ...
    // Now you dispose fireloop
    this.disposeFL();
  }
}
````

I hope this helps you understand how to write an Angular App component by these examples.

Please rate from 1 to 5 so depending on that I might add this on the official documentation

Cheers
Jon

**Comment by rekless5** [comment]
@jonathan-casarrubias Thank you. I was writing this as a simple test to figure out the loopback component. However with you're edits it's still not updating the list when it is added. Should there be a change event in the socket network log? Here is a gif of what is happening.


![networklog 1](https://user-images.githubusercontent.com/11300593/29578432-4880a99e-873d-11e7-881d-81ce4da68101.gif)

**Comment by jonathan-casarrubias** [comment]
@rekless5 I have found the issue.

Basically all the problem is because the todo model is all lowercased, though LoopBack might work with all lowercased models, FireLoop requires to follow the CamelCased pattern for your models.

Basically the only thing you need to do is to change your model configuration to CamelCase and will work

**Comment by rekless5** [comment]
@jonathan-casarrubias That's it. Thanks so much for your help!

**Comment by jonathan-casarrubias** [comment]
I'm glad it worked now for you, I hope you to build cool things with this platform

Cheers
Jon
