### ISSUE TITLE
Cannot read property 'IO' of undefined

### ISSUE THREAD

**Issue by MROALI** [mean-expert-official/loopback-component-realtime#45]
I am getting the following error when trying creating from boot script  a record in a json model which contains an array of string property .

my model is like : 
The variants field is generating the problem :

 "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "variants": {
      "type": [
        "string"
      ],
      "required": true
    }

brandname = "test";
variant = ["1 item","2 Items", "3 Items"];

myModel.create([
                  {
                      name: brandName,
                      variants : variants
                  }

It seems that array of string property is not supported ???

**error  :** 
var retval = fn(context, next);
TypeError: Cannot read property 'IO' of undefined
....\loopback-component-realtime\dist\mixins\fire-loop.js:32:25

When i change in mixins fireloop to false, it works ???

**Comment by jonathan-casarrubias** [comment]
@MROALI hello and thanks for reaching out,

Hey so... for me it seems that you have an asynchronous issue. If you need that you model is able to create Real-Time connections, then you need to keep the FireLoop mixing as true, but also within your boot script, you will need to wait until fireloop is ready.

````js
module.exports = function(app) {
   app.on('fire-connection-started', () => {
     // do your things in here.
   })
}
````

I hope this helps you clarify your problem

Cheers
Jon

**Comment by MROALI** [comment]
@jonathan-casarrubias Hello, you have reason its is an asynchronous issues.

Thanks for your answer. 

It works now :)  :+1:
